### ISSUE TITLE
UWP services asking for connectivity again and again

### ISSUE THREAD

**Issue by MandeepSBawa** [henrypp/simplewall#1294]
![image](https://user-images.githubusercontent.com/112701554/188141135-7de5e8dd-6527-4cf4-a959-f176a05df026.png)

I have created rules, and also tried to add them again. But these pop-ups to allow the connection are coming again and again. 

Please let me know how to solve this.

**Comment by coolrainbow20** [comment]
I also experience that problem and it's driving me nuts. I even have to disable the blocker just to use UWP apps.  Also I don't think there should be any SID displayed but rather the UWP app name instead. It didn't happen with older version of this AFAIK.

**Comment by THEBOSS619** [comment]
Same issue here..

**Comment by calran** [comment]
I'm having the same symptoms every few minutes, in my case it seems to be unique to Azure AD authentication on my work system.
![sid uwp](https://user-images.githubusercontent.com/5678833/188350839-744c758a-08c3-4ca1-a55e-61ad44236d3f.png)

**Comment by MandeepSBawa** [comment]
I uninstalled Simplewall and Re-installed again. Made sure no rules or settings were left. 

After this process all is ok. You can also try to reset all settings using the reset button in the settings before uninstalling.

**Comment by chris-kwl** [comment]
Same here with the weather app since a few hours.  
App is listed under "Apps with internet access" but connections are blocked and also logged as blocked
Pop-up is also coming again and again, but not always there is a break from ~1m

<details>
  <summary>logs:</summary>
  
  
  ```
"‎06.‎09.‎2022 ‏‎19:34:08","xxx","S-1-15-2-283421221-3183566570-1718213290-751554359-3541592344-2312209569-3374928651","192.168.8.142","49314","52.98.175.2","443 (https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","Internal\BlockConnection","#2267828","Outbound","Blocked"
"‎06.‎09.‎2022 ‏‎19:34:08","xxx","S-1-15-2-283421221-3183566570-1718213290-751554359-3541592344-2312209569-3374928651","192.168.8.142","49315","52.98.152.194","443 (https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","Internal\BlockConnection","#2267828","Outbound","Blocked"
"‎06.‎09.‎2022 ‏‎19:34:08","xxx","S-1-15-2-283421221-3183566570-1718213290-751554359-3541592344-2312209569-3374928651","192.168.8.142","49316","40.99.150.34","443 (https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","Internal\BlockConnection","#2267828","Outbound","Blocked"
"‎06.‎09.‎2022 ‏‎19:34:08","xxx","S-1-15-2-283421221-3183566570-1718213290-751554359-3541592344-2312209569-3374928651","192.168.8.142","49317","52.98.152.242","443 (https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","Internal\BlockConnection","#2267828","Outbound","Blocked"
"‎06.‎09.‎2022 ‏‎19:34:09","xxx","S-1-15-2-283421221-3183566570-1718213290-751554359-3541592344-2312209569-3374928651","192.168.8.142","49318","204.79.197.222","443 (https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","Internal\BlockConnection","#2267828","Outbound","Blocked"
"‎06.‎09.‎2022 ‏‎19:34:09","xxx","S-1-15-2-283421221-3183566570-1718213290-751554359-3541592344-2312209569-3374928651","192.168.8.142","49319","13.107.22.200","443 (https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","Internal\BlockConnection","#2267828","Outbound","Blocked"
"‎06.‎09.‎2022 ‏‎19:34:09","xxx","S-1-15-2-283421221-3183566570-1718213290-751554359-3541592344-2312209569-3374928651","192.168.8.142","49320","131.253.33.200","443 (https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","Internal\BlockConnection","#2267828","Outbound","Blocked"
"‎06.‎09.‎2022 ‏‎19:34:11","xxx","S-1-15-2-2040986369-264322980-3882385089-1970153872-3662121739-3363227934-2464603330","192.168.8.142","49321","204.79.197.203","443 (https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","Internal\BlockConnection","#2267828","Outbound","Blocked"
"‎06.‎09.‎2022 ‏‎19:34:11","xxx","S-1-15-2-2040986369-264322980-3882385089-1970153872-3662121739-3363227934-2464603330","192.168.8.142","49322","52.239.149.196","443 (https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","Internal\BlockConnection","#2267828","Outbound","Blocked"
"‎06.‎09.‎2022 ‏‎19:34:11","xxx","S-1-15-2-2040986369-264322980-3882385089-1970153872-3662121739-3363227934-2464603330","192.168.8.142","49324","204.79.197.203","443 (https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","Internal\BlockConnection","#2267828","Outbound","Blocked"
"‎06.‎09.‎2022 ‏‎19:34:13","xxx","S-1-15-2-2040986369-264322980-3882385089-1970153872-3662121739-3363227934-2464603330","192.168.8.142","49326","204.79.197.203","443 (https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","Internal\BlockConnection","#2267828","Outbound","Blocked"
"‎06.‎09.‎2022 ‏‎19:34:31","xxx","S-1-15-2-2040986369-264322980-3882385089-1970153872-3662121739-3363227934-2464603330","192.168.8.142","49329","204.79.197.203","443 (https)","tcp","FWPM_LAYER_ALE_AUTH_CONNECT_V4","Internal\BlockConnection","#2267828","Outbound","Blocked"
  ```
  
</details>


<details>
  <summary>error logs:</summary>
  

  
  ```
"Error","‎06.‎09.‎2022 ‏‎19:20:14","_wfp_createrulefilter","0x00000000","S-1-15-2-2040986369-264322980-3882385089-1970153872-3662121739-3363227934-2464603330","3.6.6","10.0 build 22000"
"Error","‎06.‎09.‎2022 ‏‎19:22:45","_wfp_createrulefilter","0x00000000","S-1-15-2-2040986369-264322980-3882385089-1970153872-3662121739-3363227934-2464603330","3.6.6","10.0 build 22000"
"Error","‎06.‎09.‎2022 ‏‎19:22:51","_wfp_createrulefilter","0x00000000","S-1-15-2-2040986369-264322980-3882385089-1970153872-3662121739-3363227934-2464603330","3.6.6","10.0 build 22000"
"Error","‎06.‎09.‎2022 ‏‎19:32:32","_wfp_createrulefilter","0x00000000","S-1-15-2-2040986369-264322980-3882385089-1970153872-3662121739-3363227934-2464603330","3.6.6","10.0 build 22000"
"Error","‎06.‎09.‎2022 ‏‎19:34:30","_wfp_createrulefilter","0x00000000","S-1-15-2-2040986369-264322980-3882385089-1970153872-3662121739-3363227934-2464603330","3.6.6","10.0 build 22000"
"Error","‎06.‎09.‎2022 ‏‎19:38:42","_wfp_createrulefilter","0x00000000","S-1-15-2-2040986369-264322980-3882385089-1970153872-3662121739-3363227934-2464603330","3.6.6","10.0 build 22000"
"Error","‎06.‎09.‎2022 ‏‎19:39:48","_wfp_createrulefilter","0x00000000","S-1-15-2-2040986369-264322980-3882385089-1970153872-3662121739-3363227934-2464603330","3.6.6","10.0 build 22000"
"Error","‎06.‎09.‎2022 ‏‎19:40:54","_wfp_createrulefilter","0x00000000","S-1-15-2-2040986369-264322980-3882385089-1970153872-3662121739-3363227934-2464603330","3.6.6","10.0 build 22000"
"Error","‎06.‎09.‎2022 ‏‎19:42:00","_wfp_createrulefilter","0x00000000","S-1-15-2-2040986369-264322980-3882385089-1970153872-3662121739-3363227934-2464603330","3.6.6","10.0 build 22000"
"Error","‎06.‎09.‎2022 ‏‎19:43:18","_wfp_createrulefilter","0x00000000","S-1-15-2-2040986369-264322980-3882385089-1970153872-3662121739-3363227934-2464603330","3.6.6","10.0 build 22000"

  ```
  
</details>

<details>
  <summary>System (German)</summary>
  
  
  ```
Edition	Windows 11 Pro
Version	21H2
Installiert am	‎16.‎10.‎2021
Betriebssystembuild	22000.856
Leistung	Windows Feature Experience Pack 1000.22000.856.0
simplewall v.3.6.6 
  ```
  
</details>

**Comment by ZacharyElkins** [comment]
Same here. It also deleted my existing database of rules.

I reset all settings, uninstalled, and reinstalled. That seems to have fixed it. Always good to keep a backup of the rules, however I think I'll just go with a clean slate for now.

**Comment by henrypp** [comment]
It happened after downloading and installing updates by simplewall. Just press "Refresh" after that and all UWP apps are going back.

**Comment by henrypp** [comment]
This is fixed in next release.

**Comment by underlines** [comment]
This is definately NOT fixed and still happens:

- Windows 11 Pro EN
- Simplewall 3.6.7 x64
- Whatsapp (UWP App from Microsoft Store)

Stops working, having repeated popups with the GUID instead of the name, even clicking allow won't give the UWP app access to the internet anymore. The only solution seems to be clicking "Refresh"

**Comment by fragtion** [comment]
I can attest that this isn't fixed in 3.7.1.  Fortuantely, pressing "Refresh" is an effective workaround in the meanwhile.
Please fix
