### ISSUE TITLE
Show log button does not work as expected

### ISSUE THREAD

**Issue by secured2k** [henrypp/simplewall#1757]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

3.8

### Windows version

10 22H2

### Steps to reproduce

The program is running with elevated permissions under the same user context.
Log file is saved to %Userprofile%\simplewall.log. It can be opened and viewed manually. Data inside the file is valid.

Click the Show log button or use the shortcut key (CTRL+I).

### Expected behavior

The log file should open using the viewer configured. 

### Actual behavior

If enable packet logging interface is enabled, nothing happens.
If enable packet logging interface is disabled, notepad opens and displays the contents of notepad.exe.

**Comment by OlsiIgitt** [comment]
I can confirm this bug! It occurs at least since version 3.7.7:
Having definined an external Log viewer app and using "Show Log" will start this external viewer with showing the defined simplewall.log file and additional the defined viewer exe file itself!

**Comment by henrypp** [comment]
now it is fixed

**Comment by OlsiIgitt** [comment]
I am using the (newest) version 3.8.1, and the problem persists.

> now it is fixed
Do you mean version >= 3.8.2 ???

**Comment by Marabunta159** [comment]
Not fixed. Protocol Tab is empty. Logfile exists and can be opend. Installed today 3.8.2 on WIndows 11 x64

Message:
component of the object path was not a directory object.

Status:
-1073741767 (0xC0000039)

Description:
"C:\WINDOWS\notepad.exe" C:\Users\user\simplewall.log

**Comment by henrypp** [comment]
Sorry for waiting, i release 3.8.3 when i finish it, and problem in idiotic NT function [NtCreateUserProcess](https://github.com/henrypp/routine/blob/97c9331e1ad74bc2ac0d1f219b7ecda4e61d7d51/src/routine.c#L9214) which is not documented and realized like idiot creating this func, does not support Image Hijack and some other problems (like i need to close file and section which you open/create every time), <s>thanks</s> @microsoft.

**Comment by henrypp** [comment]
@ReaperIM what a hell are u talking about?

**Comment by henrypp** [comment]
@ReaperIM 

1. it is offtopic
2. it is access denied problem of your software which u installed and not right configured
