### ISSUE TITLE
Simplewall update

### ISSUE THREAD

**Issue by drozdowsky** [henrypp/simplewall#371]
I have "simple wall update" notification even on newest release - when I click update (after it downloaded previously) - nothing happens (app even doesn't start)

**Comment by TontyTon** [comment]
You should try uninstalling and then reinstalling SW. There was some read-only file issue in one the recent versions, which could be causing your problem.
Remember to backup your apps and custom rules.

---
If your problem is already solved then you must close the issue.

**Comment by drozdowsky** [comment]
Just uninstalled and installed 3.0 manually. Will update this issue when update is available.

Thank you for great 3.0 update @henrypp !!!

**Comment by drozdowsky** [comment]
Update to 3.0.1 using built-in update is still not possible for me.
Application downloads, closes and then nothing.

**Comment by henrypp** [comment]
Answer https://github.com/henrypp/simplewall/issues/249#issuecomment-436755685
