### ISSUE TITLE
Crash when adding custom rule

### ISSUE THREAD

**Issue by synchr** [henrypp/simplewall#89]
Version: 2.0.20, 64-bit (Unicode) on Windows 10

To reproduce:
- Open settings>Custom rules
- Delete all custom rules
- Add a new rule with arbitrary name and IP
- Simplewall crashes

It can also happen without deleting all the rules, this just seems to trigger the bug reliably.

**Comment by henrypp** [comment]
fixed

**Comment by henrypp** [comment]
Or not? Please check 2.1b

**Comment by synchr** [comment]
It's still crashing. I was able to reproduce the crash pretty quickly.

**Comment by henrypp** [comment]
Ok.

**Comment by henrypp** [comment]
Check 2.1.2

**Comment by synchr** [comment]
Tested 2.1.3 and it seems to have fixed this bug
